# This file was generated by GoReleaser. DO NOT EDIT.
cask "dacfy" do
  desc "dacfy is a lightweight tool that lets you manage ClickHouse database objects as code."
  homepage "https://github.com/nicola-strappazzon/dacfy"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dacfy"

  on_macos do
    on_intel do
      url "https://github.com/nicola-strappazzon/dacfy/releases/download/v1.0.2/dacfy_darwin_amd64.tar.gz"
      sha256 "e378f28c964436533be76278b6b5a49dcb2060d8648584a6e2885affbffb2828"
    end
    on_arm do
      url "https://github.com/nicola-strappazzon/dacfy/releases/download/v1.0.2/dacfy_darwin_arm64.tar.gz"
      sha256 "1bbc98f3af1c2cee1acd1ec6c3bf89e73a15c4c3cc8f1e7b09d16f9ec615ed61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nicola-strappazzon/dacfy/releases/download/v1.0.2/dacfy_linux_amd64.tar.gz"
      sha256 "6edfbad069b19013d502ae12d654aaeddc808209666d708f568f8fa69e40a5e7"
    end
    on_arm do
      url "https://github.com/nicola-strappazzon/dacfy/releases/download/v1.0.2/dacfy_linux_arm64.tar.gz"
      sha256 "ef1318689ee7e778203c0777e9d3ed532f1063c338b804cb007a8d9e16394ae0"
    end
  end

  # No zap stanza required
end
