# This file was generated by GoReleaser. DO NOT EDIT.
cask "password-manager" do
  name "password-manager"
  desc "password-manager is another Unix-style password manager written in Go."
  homepage "https://github.com/nicola-strappazzon/password-manager"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"
  bash_completion "completions/pm.bash"

  on_macos do
    on_intel do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_amd64.tar.gz"
      sha256 "13808f60c713e37170f06215efa6784eece1f37e831e19e20e2d389679067801"
    end
    on_arm do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_arm64.tar.gz"
      sha256 "f16e4938fe4860090dbef537dd4a8db00b4edaa90fe7160db1f0d030c76964a8"
    end
  end

  # No zap stanza required
end
