# This file was generated by GoReleaser. DO NOT EDIT.
cask "password-manager" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "d71908831b8ad907d70227f94afa50f2538b46f52f56137f74f5617abaa22172"
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "22cd61ea92441757825c2e27e0a9a9a7081de73b45a68a4867733adc6307d5fe"
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f00ef161be550721260305b8779c0759ccd3eb02e3d758dc6fd1779cc4eea2dd"
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "477f60fe7675376bcdb636590aad6e1d6c908503c76a895816231a409c474b58"
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_linux_arm64.tar.gz"
    end
  end

  name "password-manager"
  desc "password-manager is another Unix-style password manager written in Go."
  homepage "https://github.com/nicola-strappazzon/password-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"
  bash_completion "completions/pm.bash"

  # No zap stanza required

end
