# This file was generated by GoReleaser. DO NOT EDIT.
cask "password-manager" do
  version "0.9.0"

  on_macos do
    on_intel do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_amd64.tar.gz"
      sha256 "9eb7c906c67b389960d46c65bdcd33e15fd4488bc8985ede8b79f4dec0ee31d1"
    end
    on_arm do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_darwin_arm64.tar.gz"
      sha256 "10a857d40b821e7fd15a977031ec1ba0c771d4d3d4ddf589c23dddb8ae83e9e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_linux_amd64.tar.gz"
      sha256 "94f77ccc149aaad552c5450734da501fb2d6780f8cd861c3fce7f70b06145c06"
    end
    on_arm do
      url "https://github.com/nicola-strappazzon/password-manager/releases/download/v#{version}/password-manager_linux_arm64.tar.gz"
      sha256 "7491914079db1d75eab3d9145735d3bef0100f613a7424b5351575132cb6fb7b"
    end
  end

  name "password-manager"
  desc "password-manager is another Unix-style password manager written in Go."
  homepage "https://github.com/nicola-strappazzon/password-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"
  bash_completion "completions/pm.bash"

  # No zap stanza required

end
